<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-FQJ2DVAE" ignored="0" name="COS05_RegularStock Test(failed)(failed)" tests="4" failures="1" timestamp="26 Sep 2020 08:03:12 GMT" time="49.022" errors="0">
  <testcase name="RegularStocks" time="14.735" classname="com.cosacs.TestCases.COS05_RegularStock"/>
  <testcase name="CreateRegularStock" time="20.652" classname="com.cosacs.TestCases.COS05_RegularStock">
    <failure type="java.lang.AssertionError" message="expected [Product saved successfully ] but found [Product saved successfully]">
      <![CDATA[java.lang.AssertionError: expected [Product saved successfully ] but found [Product saved successfully]
at com.cosacs.TestCases.COS05_RegularStock.CreateRegularStock(COS05_RegularStock.java:140)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- CreateRegularStock -->
  <testcase name="ProductDetails" time="0.0" classname="com.cosacs.TestCases.COS05_RegularStock">
    <skipped/>
  </testcase> <!-- ProductDetails -->
  <testcase name="ProductEnquiry" time="0.0" classname="com.cosacs.TestCases.COS05_RegularStock">
    <skipped/>
  </testcase> <!-- ProductEnquiry -->
</testsuite> <!-- COS05_RegularStock Test(failed)(failed) -->
