<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-FQJ2DVAE" ignored="0" name="COS_18_Directreceipt Test" tests="3" failures="1" timestamp="24 Sep 2020 12:17:18 GMT" time="91.628" errors="0">
  <testcase name="Directreceipt_verify_stockcount" time="23.138" classname="com.cosacs.TestCases.COS_18_Directreceipt"/>
  <testcase name="Directreceipt_form" time="40.847" classname="com.cosacs.TestCases.COS_18_Directreceipt"/>
  <testcase name="Directreceipt_stockcount_afterDRN" time="15.484" classname="com.cosacs.TestCases.COS_18_Directreceipt">
    <failure type="java.lang.AssertionError" message="expected [0] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [2]
at com.cosacs.TestCases.COS_18_Directreceipt.Directreceipt_stockcount_afterDRN(COS_18_Directreceipt.java:234)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Directreceipt_stockcount_afterDRN -->
</testsuite> <!-- COS_18_Directreceipt Test -->
